spring.application.name=core
# Підключення до твоєї бази в Докері (порт 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/sellora_db
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-className=org.postgresql.Driver

# Вказуємо шлях до головного файлу міграцій
spring.liquibase.changelog=classpath:db/changelog/db.changelog-master.yaml

